### ISSUE TITLE
[Bug]: Could not pass event PlayerItemConsumeEvent to OmegaVision v2.5.7

### ISSUE THREAD

**Issue by baailey** [OmegaWeaponDev/OmegaVision#17]
### Issue Description

Not sure exactly.

### Steps to Reproduce

No clue,

### Error Messages

```shell
16.12 13:18:22 [Server] ERROR Could not pass event PlayerItemConsumeEvent to OmegaVision v2.5.7
16.12 13:18:22 [Server] INFO java.lang.NullPointerException: Cannot invoke "java.util.Map.put(Object, Object)" because the return value of "java.util.Map.get(Object)" is null
16.12 13:18:22 [Server] INFO at me.omegaweapondev.omegavision.utils.UserDataHandler.setEffectStatus(UserDataHandler.java:122) ~[OmegaVision-2.5.7.jar:?]
16.12 13:18:22 [Server] INFO at me.omegaweapondev.omegavision.events.PlayerListener.onBucketUse(PlayerListener.java:220) ~[OmegaVision-2.5.7.jar:?]
16.12 13:18:22 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor152.execute(Unknown Source) ~[?:?]
16.12 13:18:22 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
16.12 13:18:22 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:git-Paper-66]
16.12 13:18:22 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
16.12 13:18:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
16.12 13:18:22 [Server] INFO at net.minecraft.world.entity.LivingEntity.completeUsingItem(LivingEntity.java:3807) ~[?:?]
16.12 13:18:22 [Server] INFO at net.minecraft.server.level.ServerPlayer.completeUsingItem(ServerPlayer.java:1704) ~[?:?]
16.12 13:18:22 [Server] INFO at net.minecraft.world.entity.LivingEntity.updateUsingItem(LivingEntity.java:3669) ~[?:?]
16.12 13:18:22 [Server] INFO at net.minecraft.server.level.ServerPlayer.updateUsingItem(ServerPlayer.java:2282) ~[?:?]
16.12 13:18:22 [Server] INFO at net.minecraft.world.entity.LivingEntity.updatingUsingItem(LivingEntity.java:3650) ~[?:?]
16.12 13:18:22 [Server] INFO at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2868) ~[?:?]
16.12 13:18:22 [Server] INFO at net.minecraft.world.entity.player.Player.tick(Player.java:268) ~[?:?]
16.12 13:18:22 [Server] INFO at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:669) ~[?:?]
16.12 13:18:22 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:315) ~[?:?]
16.12 13:18:22 [Server] INFO at net.minecraft.network.Connection.tick(Connection.java:526) ~[?:?]
16.12 13:18:22 [Server] INFO at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
16.12 13:18:22 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636) ~[paper-1.18.jar:git-Paper-66]
16.12 13:18:22 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.jar:git-Paper-66]
16.12 13:18:22 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.jar:git-Paper-66]
16.12 13:18:22 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.jar:git-Paper-66]
16.12 13:18:22 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-66]
16.12 13:18:22 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Expected Behaviour

No error?

### Debug Information

https://pastebin.com/iSn4tkyW

**Comment by OmegaWeaponDev** [comment]
Hi @baailey

Please try this version as it should eliminate the error. Let me know how it goes.

[OmegaVision-2.5.8.zip](https://github.com/OmegaWeaponDev/OmegaVision/files/7724210/OmegaVision-2.5.8.zip)
