### ISSUE TITLE
Error in console when user does not have permission 

### ISSUE THREAD

**Issue by SmallSansSerif** [OmegaWeaponDev/OmegaVision#8]
[22:41:45 INFO]: Headle55_h0rs3mn issued server command: /nv
[22:41:45 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'nv' in plugin OmegaVision v2.4.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Purpur-1064]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.5.jar:git-Purpur-1064]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2301) ~[?:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2116) ~[?:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2069) ~[?:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1064]  
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1335) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1328) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1304) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1148) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1064]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at me.omegaweapondev.omegavision.utils.MessageHandler.string(MessageHandler.java:22) ~[?:?]
        at me.omegaweapondev.omegavision.command.ToggleCommand.toggleCommand(ToggleCommand.java:59) ~[?:?]
        at me.omegaweapondev.omegavision.command.ToggleCommand.execute(ToggleCommand.java:44) ~[?:?]
        at me.omegaweapondev.omegavision.library.commands.GlobalCommand.onCommand(GlobalCommand.java:17) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Purpur-1064]
        ... 19 more

**Comment by OmegaWeaponDev** [comment]
Hi SmallSansSerif,

Thanks for reporting the error. I will have a look into it now and release an update once the issue has been resolved. 

Thanks,
OmegaWeaponDev

**Comment by OmegaWeaponDev** [comment]
Hi SmallSansSerif,
Thanks for reporting the issue.

Please update to version 2.4.8 as it should resolve the issue. If it continues or new errors arise from this version let me know and I will be happy to take a look at them. 

Thanks,
OmegaWeaponDev

**Comment by SmallSansSerif** [comment]
Just tried the new version and getting this error even after resetting the config:

[14:09:46 INFO]: SmallSansSerif issued server command: /nv
[14:09:46 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'nv' in plugin OmegaVision v2.4.8
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Purpur-1064]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.5.jar:git-Purpur-1064]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2301) ~[?:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2116) ~[?:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2069) ~[?:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1335) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1328) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1304) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1148) ~[patched_1.16.5.jar:git-Purpur-1064]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1064]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at me.omegaweapondev.omegavision.utils.MessageHandler.string(MessageHandler.java:25) ~[?:?]
        at me.omegaweapondev.omegavision.utils.NightVisionToggle.nightVisionEnable(NightVisionToggle.java:80) ~[?:?]
        at me.omegaweapondev.omegavision.command.ToggleCommand.toggleCommand(ToggleCommand.java:78) ~[?:?]
        at me.omegaweapondev.omegavision.command.ToggleCommand.execute(ToggleCommand.java:44) ~[?:?]
        at me.omegaweapondev.omegavision.library.commands.GlobalCommand.onCommand(GlobalCommand.java:17) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Purpur-1064]
        ... 19 more

**Comment by OmegaWeaponDev** [comment]
Please try version 2.4.9 as this SHOULD resolve the issue properly this time. 

Thanks,
OmegaWeaponDev
