### ISSUE TITLE
Join event error?

### ISSUE THREAD

**Issue by ClickyMCSMP** [OmegaWeaponDev/OmegaVision#9]
### issue-description

Getting this error after joining.
I haven't edited anything within the plugin, and was only provided the jar.

### Error Messages

https://paste.helpch.at/agafunobec.sql

### Expected Behaviour

I think... the expected behaviour is to not produce console errors.

### Debug Information

https://imgur.com/a/Bghtxhs

### Logs and Configs

https://paste.helpch.at/celoqajipa.makefile - Messages
https://paste.helpch.at/tetucuwugi.shell - Config

Both default - nothing edited.

**Comment by OmegaWeaponDev** [comment]
Hi, 

Please try using this version:
[OmegaVision-2.5.0.zip](https://github.com/OmegaWeaponDev/OmegaVision/files/7504786/OmegaVision-2.5.0.zip)

It should hopefully fix the join issue.

Thanks

**Comment by ClickyMCSMP** [comment]
> Hi,
> 
> Please try using this version: [OmegaVision-2.5.0.zip](https://github.com/OmegaWeaponDev/OmegaVision/files/7504786/OmegaVision-2.5.0.zip)
> 
> It should hopefully fix the join issue.
> 
> Thanks

This did not fix it.

`[20:07:25 ERROR]: Could not pass event PlayerJoinEvent to OmegaVision v2.5.0
java.lang.NullPointerException: Cannot invoke "java.util.Map.getOrDefault(Object, Object)" because the return value of "java.util.Map.get(Object)" is null
        at me.omegaweapondev.omegavision.utils.UserDataHandler.getEffectStatus(UserDataHandler.java:93) ~[OmegaVision-2.5.0.jar:?]
        at me.omegaweapondev.omegavision.events.PlayerListener.onPlayerJoin(PlayerListener.java:49) ~[OmegaVision-2.5.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor155.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-"8575248"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-"8575248"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-"8575248"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[patched_1.17.1.jar:git-Paper-"8575248"]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:360) ~[patched_1.17.1.jar:git-Paper-"8575248"]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:302) ~[patched_1.17.1.jar:git-Paper-"8575248"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:307) ~[app:?]
        at net.minecraft.network.Connection.tick(Connection.java:555) ~[app:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1648) ~[patched_1.17.1.jar:git-Paper-"8575248"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-"8575248"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-"8575248"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-"8575248"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-"8575248"]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]`
